- bin/cylc-cat-log
- lib/cylc/remote.py
Hi @hjoliver I was looking at the test failure I mentioned in #2503 and have come up with some fixes and minor modifications independently.
I have no idea that you would be looking at them as well at this sort of time on a Friday. (Should have known better!) I have now incorporated my change with yours. I think I should at least make a PR on your branch to make you aware of my changes. Feel free to use or ignore as you wish.
My changes include:
- When using `qcat`, don't check for existence of job log in the usual location.
- (This one is essential. The rest are mostly style.)
- Allow `--debug` mode to propagate to the remote `cylc cat-log` command.
- Use argument list instead of argument string for the shell command that is run via SSH.
- Instead of `--remote-mode …
> cat-log --remote: improve interface

- cylc/flow/scheduler.py
- tests/flakyfunctional/cylc-poll/16-execution-time-limit/flow.cylc
- tests/flakyfunctional/cylc-poll/16-execution-time-limit/reference.log
- tests/functional/broadcast/00-simple.t
- tests/functional/broadcast/00-simple/flow.cylc
- tests/functional/cylc-play/05-start-task.t
- tests/functional/jinja2/05-commandline.t
- tests/functional/job-file-trap/00-sigusr1.t
- tests/functional/job-file-trap/02-pipefail.t
- tests/functional/modes/02-dummy-message-outputs.t
- tests/functional/remote/03-polled-task-started.t
- tests/functional/restart/28-execution-timeout.t
- tests/functional/spawn-on-demand/07-abs-triggers.t
* Logging level for trigger items was reduced causing failures when test workflows were not run in debug mode.
* Bump the log level up when running in reftest (or genref) modes to avoid the issue.
> reftest: always log triggering events at info level for reftests

- cylc/flow/network/schema.py
* Set default values for args to allow them to be fired without
additional context information.
* Add descriptions.
* Centralise the "flow" argument so it can be easily added to other
mutations later.
> graphql: metadata for trigger mutation

- cylc/flow/scripts/trigger.py
- cylc/flow/task_pool.py
- tests/functional/flow-triggers/12-all-future-multi.t
- tests/functional/flow-triggers/12-all-future-multi/flow.cylc
- tests/functional/flow-triggers/12-all-future-multi/reference.log
- tests/integration/test_trigger.py
Addresses one issue where a single `--flow=new` trigger can result in multiple new flows, e.g. in the following example three new flows would be created:
```console
$ cylc trigger --flow=new <id>// //1/a //2/a //3/a
```
Also add a test to cover the behaviour of `--flow=all` when multiple flows are present.
> Flow triggers wait

- tests/integration/test_task_pool.py
- tests/integration/utils/flow_tools.py
* Tests https://github.com/cylc/cylc-flow/pull/5334
This fails on upstream/8.1.x with the following traceback:
```
Traceback (most recent call last):    
File "~/cylc-flow/cylc/flow/scheduler.py", line 687, in start
await self.configure()
File "~/cylc-flow/cylc/flow/scheduler.py", line 476, in configure                         
self._load_pool_from_db()    
File "~/cylc-flow/cylc/flow/scheduler.py", line 738, in _load_pool_from_db                         
self.pool.load_db_task_pool_for_restart)    
File "~/cylc-flow/cylc/flow/rundb.py", line 894, in select_task_pool_for_restart                         
callback(row_idx, list(row))    
File "~/cylc-flow/cylc/flow/task_pool.py", line 508, in load_db_task_pool_for_restart …
```
> restart: test prereq changes are applied on restart

- cylc/flow/task_pool.py
- cylc/flow/task_proxy.py
- tests/integration/test_scheduler.py
- tests/integration/test_task_pool.py
> **Built On:** #5328
If a prerequisite is missing from the database on reload/restart, then look through the task outputs table to see whether it is satisfied.
Two issues/questions:
1. I'm not sure how to square this with the data store without duplicating the database calls.
2. This PR marks all satisfied prerequisites as `satisfied naturally`. I think the information is lost by this point, is there a more suitable value e.g `satisfied from DB`?
> pool: load missing prerequisite status from database

- cylc/flow/task_pool.py
- tests/integration/test_task_pool.py
Covers the last three points of #5334
* update datastore
* new test for this case
* "satisfied by DB" (or similar)
> task pool: update data store when prereqs change on reload

- cylc/flow/scripts/completion_server.py
- tests/integration/scripts/test_completion_server.py
- tests/unit/scripts/test_completion_server.py
* Support the `--pre` and `--out` arguments to `cylc set`.
* This requires the task ID(s) to be provided *before* the `--pre` / `--out` option because otherwise we don't have the required information to complete the arguments.
* This lists prereqs/outputs from `cylc show` which is currently restricted to n=1 tasks.
* This does not support completing comma separared prereqs/outputs, use the `--pre` / `--out` options multiple times to do this.
> completion_server: support "cylc set" arguments

- .github/workflows/test_fast.yml
- cylc/flow/cycling/iso8601.py
- pytest.ini
- setup.cfg
- tests/integration/test_task_pool.py
In back-compat mode the cycle point time zone is assumed to be local, whereas in normal mode it is assumed to be UTC. There was contamination of the point parse caching where the time zone would carry over from tests of back-compat vs normal mode.
Also removed pytest-env because it doesn't work with pytest-xdist (copied from master - see https://github.com/cylc/cylc-flow/pull/5826/commits/be46a11115294ab41f00b3a6a76ffacb29b28d32)
> Tests: fix cached point parse contamination between tests

- cylc/flow/prerequisite.py
- cylc/flow/task_pool.py
- cylc/flow/task_proxy.py
- cylc/flow/task_state.py
- tests/integration/test_task_pool.py
Pass tokens objects a bit deeper into the code to avoid unnecessary detokenisation / string formatting.
> tokens: avoid surplus detokenising

- cylc/flow/task_pool.py
- tests/integration/scripts/test_set.py
- tests/integration/test_task_pool.py
leading to a warning that the task was not dependent on "all".
Bug created at https://github.com/hjoliver/cylc-flow/commit/1c656ef3e53fc08fcd9886f7df65b504b8e8e23b
> Don't tokenize `--pre=all`

- cylc/flow/scripts/set.py
- cylc/flow/unicode_rules.py
- tests/functional/authentication/00-shared-fs.t
This fixes a test which was broken by log format changes but isn't run in CI.
It also adds some extra validation to the `cylc set` command to catch some likely user errors.
> cylc set stuffs

- cylc/flow/task_pool.py
- tests/integration/test_task_pool.py
(copied from https://github.com/cylc/cylc-flow/pull/5658#issuecomment-1980840903) so you don't have to follow the link.
Running a noddy workflow
```
cylc set cylc-set/basic//1/bar --pre='1/*:succeeded'
```
Gets sent successfully to the scheduler but then casuses the scheduler to fail
```
...
File "/media/tim/Data1/tims_code/metomi/cylc-flow/cylc/flow/config.py", line 2215, in get_taskdef
raise WorkflowConfigError(str(exc))
cylc.flow.exceptions.WorkflowConfigError: Illegal task name: *
```
However daft a user's choice of input to set is, I don't think it ought ever crash the scheduler: And I don't think that this is super daft thing to ask for.
> Prevent malformed `--pre` options taking the scheduler down

- cylc/flow/task_outputs.py
- cylc/flow/task_pool.py
- tests/integration/test_task_pool.py
Cylc set sorts outputs before emitting them.
if you run a simple workflow:
```ini
[scheduling]
cycling mode = integer
[[graph]]
R1 = """
foo:a & foo:b => bar
"""
[runtime]
[[foo]]
script = sleep 300
[[[outputs]]]
a = 'apple (poisoned)'
b = 'banshee'
[[bar]]
```
set it running then 
```console
cylc set set/basic//1/foo    # --out=required
```
gets the following message:
```
2024-03-11T13:48:42Z INFO - [1/foo/01:submitted] setting implied output: started
2024-03-11T13:48:42Z INFO - [1/foo/01:submitted] => succeeded
2024-03-11T13:48:42Z WARNING - [1/foo/01:succeeded] did not complete required outputs: ['a', 'b']
2024-03-11T13:48:42Z INFO - [1/foo/01:succeeded] completed output a
2024-03-11T13:48:42Z INFO - [1/bar:waiting(runahead)] added to active task pool
2024-03-11T13:48:42Z INFO - …
```
> Make set trigger outputs in order

- tests/integration/test_task_pool.py
* Ensure removed tasks are not automatically re-spawned by task pool logic.
* Ensure removed tasks can be manually re-spawned by request.
> remove: add integration tests

- cylc/flow/xtriggers/workflow_state.py
- tests/unit/xtriggers/test_workflow_state.py
Currently a WIP - replaces https://github.com/hjoliver/cylc-flow/pull/50/files
Tests for:
* workflow state xtrigger validation function
> Extra testing for fix-workflow-state-check

- cylc/flow/xtriggers/workflow_state.py
- tests/integration/conftest.py
- tests/integration/test_dbstatecheck.py
- tests/integration/test_xtrigger_mgr.py
Wrote these as part of my review.
> more tests

- cylc/flow/command_validation.py
- cylc/flow/task_pool.py
- tests/integration/test_trigger.py
- tests/unit/test_command_validation.py
https://github.com/cylc/cylc-flow/pull/6367
> Simplify flow number wrangling & improve error message

- tests/integration/test_task_pool.py
Integration test to cover https://github.com/cylc/cylc-flow/issues/6259, https://github.com/cylc/cylc-flow/issues/6260
> xtriggers: test rebuilding of xtriggers on reload

- .mailmap
- tests/integration/test_job_runner_mgr.py
> Not sure how to go about testing it.
There are only two code blocks not covered by existing tests.
This PR adds a test for the first one and gives us some more thorough testing in general.
The second uncovered code block, I think is a codecov error, it can't be right as that would suggest we aren't submitting any jobs in any tests? Might go away on re-run?
@hjoliver, note, I've raised this against your fork, but the PR has been raised from `jennan:fix_job_runner_newline` (so you'll have to push it manually)
> Fix job runner newline.add tests

- tests/functional/cylc-trigger/07-kill-trigger.t
- tests/functional/cylc-trigger/07-kill-trigger/flow.cylc
- tests/functional/cylc-trigger/07-kill-trigger/reference.log
Best I could come up with was a functional test.
> test https://github.com/cylc/cylc-flow/issues/6398

- cylc/flow/graph_parser.py
- tests/unit/test_graph_parser.py
Makes the test results deterministic.
> Sort pairs to make errors deterministic.

- cylc/flow/graph_parser.py
Conversion of pairs tuple to dict was throwing away information.
```python
pairs = ((None, 1), (None, 2))
print(dict(pairs))
>>> {None: 1}
print(dict(pairs))
>>> {None: 2}
```
> dict(was hiding stuff)

- cylc/flow/commands.py
- cylc/flow/util.py
- tests/integration/test_flow_assignment.py
- tests/integration/test_force_trigger.py
Revert the `--flow` behaviour changes on the group-trigger branch and replace it with something which maintains the previous behaviour for unconnected groups, but 
You might want to review this with `?w=1` on the end of the URL (hide whitespace changes in the force-trigger implementation)
It should trigger tasks within their flow if available, else all flows.
* N=0 tasks already have a flow assigned.
* N!=0 tasks do not yet have a flow assigned.
When we are triggering n!=0 tasks, there is no appropriate flow to run them
in (this would involve flow merge prediction), so we default to all active
flows as the least objection ate default.
Before group trigger, we triggered tasks independently, i.e. we assumed
there were no dependencies between the tasks and ran them all
simultaneously. With …
> trigger: restore n=0 flow behaviour for unconnected graphs
